name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          echo "node_modules" >> .gitignore
          git add .
          git commit -m "Deployed to GitHub Pages"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" main:gh-pages

      - name: Cleanup
        run: |
          git rm .gitignore
          git add .
          git commit -m "Cleanup gitignore"
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" main:gh-pages
